// Empty Dashboard Template
// Generated by Grafana Dashboard JSON to Jsonnet Transformer

{
  title: $title,
  tags: [],
  timezone: 'browser',
  schemaVersion: 38,
  version: 1,

  panels: [],

  time: {
    from: 'now-6h',
    to: 'now'
  }
}