// Kubernetes Dashboard Template
// Generated by Grafana Dashboard JSON to Jsonnet Transformer

{
  title: 'Kubernetes Cluster - ' + $cluster_name,
  uid: 'kubernetes-' + $cluster_name,
  tags: ['kubernetes', 'cluster', $namespace],
  timezone: 'browser',
  schemaVersion: 38,
  version: 1,

  panels: [],

  time: {
    from: 'now-6h',
    to: 'now'
  },

  refresh: '5s'
}