// Prometheus Dashboard Template
// Generated by Grafana Dashboard JSON to Jsonnet Transformer

{
  title: 'Prometheus - ' + $job_name,
  uid: 'prometheus-' + $job_name,
  tags: ['prometheus', 'metrics'],
  timezone: 'browser',
  schemaVersion: 38,
  version: 1,

  panels: [],

  time: {
    from: 'now-1h',
    to: 'now'
  },

  refresh: '15s'
}